#!/bin/bash
cd ../dataset

wget https://www.cise.ufl.edu/research/sparse/MM/144/144.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/2D_27628_bjtcai/2D_27628_bjtcai.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/2D_54019_highK/2D_54019_highK.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/333SP/333SP.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/3D_28984_Tetra/3D_28984_Tetra.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/3D_51448_3D/3D_51448_3D.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/3Dspectralwave/3Dspectralwave.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/3Dspectralwave2/3Dspectralwave2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/3dtube/3dtube.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/598a/598a.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/a0nsdsil/a0nsdsil.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/a2nnsnsl/a2nnsnsl.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/a5esindl/a5esindl.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/adaptive/adaptive.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/af_0_k101/af_0_k101.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/af_1_k101/af_1_k101.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/af_2_k101/af_2_k101.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/af_3_k101/af_3_k101.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/af_4_k101/af_4_k101.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/af_5_k101/af_5_k101.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/af_shell1/af_shell1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/af_shell10/af_shell10.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/af_shell2/af_shell2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/af_shell3/af_shell3.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/af_shell4/af_shell4.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/af_shell5/af_shell5.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/af_shell6/af_shell6.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/af_shell7/af_shell7.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/af_shell8/af_shell8.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/af_shell9/af_shell9.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/ak2010/ak2010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Andrews/Andrews.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/AS365/AS365.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/as-caida/as-caida.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/ASIC_680k/ASIC_680k.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/as-Skitter/as-Skitter.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/astro-ph/astro-ph.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/audikw_1/audikw_1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/auto/auto.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/barrier2-1/barrier2-1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/barrier2-10/barrier2-10.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/barrier2-11/barrier2-11.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/barrier2-12/barrier2-12.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/barrier2-2/barrier2-2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/barrier2-3/barrier2-3.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/barrier2-4/barrier2-4.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/barrier2-9/barrier2-9.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/bauru5727/bauru5727.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/bbmat/bbmat.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/bcsstk17/bcsstk17.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/bcsstk18/bcsstk18.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/bcsstk25/bcsstk25.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/bcsstk29/bcsstk29.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/bcsstk30/bcsstk30.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/bcsstk31/bcsstk31.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/bcsstk32/bcsstk32.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/bcsstk35/bcsstk35.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/bcsstk36/bcsstk36.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/bcsstk37/bcsstk37.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/bcsstk39/bcsstk39.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/bcsstm36/bcsstm36.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/belgium_osm/belgium_osm.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/BenElechi1/BenElechi1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/blockqp1/blockqp1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/bloweya/bloweya.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/bloweybl/bloweybl.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/bmw3_2/bmw3_2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/bmw7st_1/bmw7st_1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/bmwcra_1/bmwcra_1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/bone010/bone010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/boneS01/boneS01.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/boneS10/boneS10.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/boyd1/boyd1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/boyd2/boyd2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/brack2/brack2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/brainpc2/brainpc2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/bratu3d/bratu3d.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Bump_2911/Bump_2911.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/bundle1/bundle1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/bundle_adj/bundle_adj.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/c-42/c-42.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/c-43/c-43.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/c-45/c-45.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/c-46/c-46.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/c-47/c-47.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/c-48/c-48.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/c-49/c-49.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/c-50/c-50.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/c-51/c-51.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/c-52/c-52.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/c-53/c-53.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/c-54/c-54.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/c-55/c-55.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/c-56/c-56.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/c-57/c-57.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/c-58/c-58.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/c-59/c-59.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/c-60/c-60.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/c-61/c-61.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/c-62/c-62.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/c-62ghs/c-62ghs.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/c-63/c-63.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/c-64/c-64.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/c-64b/c-64b.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/c-65/c-65.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/c-66/c-66.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/c-66b/c-66b.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/c-67b/c-67b.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/c-68/c-68.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/c-69/c-69.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/c-70/c-70.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/c-71/c-71.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/c-73/c-73.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/c-73b/c-73b.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/ca-AstroPh/ca-AstroPh.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/ca-CondMat/ca-CondMat.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/cage14/cage14.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/cage15/cage15.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/ca-HepPh/ca-HepPh.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/caidaRouterLevel/caidaRouterLevel.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/cant/cant.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/case39/case39.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/case9/case9.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/c-big/c-big.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/cbuckle/cbuckle.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/ccc/ccc.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/cfd1/cfd1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Chebyshev4/Chebyshev4.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/circuit_4/circuit_4.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/circuit5M/circuit5M.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/circuit5M_dc/circuit5M_dc.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/citationCiteseer/citationCiteseer.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/cit-Patents/cit-Patents.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/ckt11752_dc_1/ckt11752_dc_1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/ckt11752_tr_0/ckt11752_tr_0.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/cnr-2000/cnr-2000.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/CO/CO.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/coAuthorsCiteseer/coAuthorsCiteseer.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/coAuthorsDBLP/coAuthorsDBLP.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/cond-mat-2003/cond-mat-2003.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/cond-mat-2005/cond-mat-2005.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/conf5_4-8x8-05/conf5_4-8x8-05.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/conf5_4-8x8-10/conf5_4-8x8-10.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/conf5_4-8x8-15/conf5_4-8x8-15.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/conf5_4-8x8-20/conf5_4-8x8-20.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/conf6_0-8x8-20/conf6_0-8x8-20.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/conf6_0-8x8-30/conf6_0-8x8-30.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/conf6_0-8x8-80/conf6_0-8x8-80.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/consph/consph.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/cont-201/cont-201.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/cont-300/cont-300.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/coPapersCiteseer/coPapersCiteseer.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/coPapersDBLP/coPapersDBLP.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/copter1/copter1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/CoupCons3D/CoupCons3D.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/crankseg_1/crankseg_1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/crankseg_2/crankseg_2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/crplat2/crplat2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/crystk02/crystk02.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/crystk03/crystk03.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/crystm02/crystm02.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/crystm03/crystm03.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/ct2010/ct2010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/ct20stif/ct20stif.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Cube_Coup_dt0/Cube_Coup_dt0.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Cube_Coup_dt6/Cube_Coup_dt6.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/CurlCurl_0/CurlCurl_0.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/CurlCurl_4/CurlCurl_4.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/cvxqp3/cvxqp3.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/cyl6/cyl6.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/darcy003/darcy003.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/dawson5/dawson5.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/dblp-2010/dblp-2010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/dc3/dc3.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/de2010/de2010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/debr/debr.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/delaunay_n15/delaunay_n15.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/delaunay_n16/delaunay_n16.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/delaunay_n17/delaunay_n17.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/delaunay_n18/delaunay_n18.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/delaunay_n19/delaunay_n19.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/delaunay_n20/delaunay_n20.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/delaunay_n21/delaunay_n21.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/delaunay_n22/delaunay_n22.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/denormal/denormal.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/dictionary28/dictionary28.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/dielFilterV2clx/dielFilterV2clx.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/dielFilterV2real/dielFilterV2real.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/dielFilterV3clx/dielFilterV3clx.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Dubcova1/Dubcova1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Dubcova3/Dubcova3.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/e40r0100/e40r0100.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/EAT_RS/EAT_RS.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/ecology1/ecology1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/ecology2/ecology2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/email-Enron/email-Enron.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Emilia_923/Emilia_923.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/engine/engine.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/enron/enron.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/eu-2005/eu-2005.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/ex11/ex11.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/ex19/ex19.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/F1/F1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/F2/F2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Fault_639/Fault_639.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/fcondp2/fcondp2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/fem_hifreq_circuit/fem_hifreq_circuit.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/filter3D/filter3D.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/finance256/finance256.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Flan_1565/Flan_1565.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/flickr/flickr.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/foldoc/foldoc.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Freescale1/Freescale1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/fullb/fullb.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/FullChip/FullChip.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/fxm4_6/fxm4_6.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/G2_circuit/G2_circuit.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/G3_circuit/G3_circuit.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Ga10As10H30/Ga10As10H30.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Ga19As19H42/Ga19As19H42.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Ga3As3H12/Ga3As3H12.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Ga41As41H72/Ga41As41H72.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/GaAsH6/GaAsH6.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/gas_sensor/gas_sensor.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Ge87H76/Ge87H76.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Ge99H100/Ge99H100.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/gearbox/gearbox.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Geo_1438/Geo_1438.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/gridgena/gridgena.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/gsm_106857/gsm_106857.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/gupta1/gupta1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/gupta2/gupta2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/gupta3/gupta3.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/gyro/gyro.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/gyro_k/gyro_k.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/gyro_m/gyro_m.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/H2O/H2O.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/halfb/halfb.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Hamrle3/Hamrle3.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/hangGlider_4/hangGlider_4.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/hangGlider_5/hangGlider_5.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/helm2d03/helm2d03.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/helm3d01/helm3d01.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/hi2010/hi2010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/hollywood-2009/hollywood-2009.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/hood/hood.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Hook_1498/Hook_1498.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/HTC_336_4438/HTC_336_4438.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/HTC_336_9129/HTC_336_9129.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/hugetric-00000/hugetric-00000.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/human_gene1/human_gene1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/human_gene2/human_gene2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/HV15R/HV15R.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/ibm_matrix_2/ibm_matrix_2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/igbt3/igbt3.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/in-2004/in-2004.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/inlet/inlet.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/inline_1/inline_1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/ins2/ins2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/italy_osm/italy_osm.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/jan99jac120sc/jan99jac120sc.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/juba40k/juba40k.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/k3plates/k3plates.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/kim1/kim1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/kkt_power/kkt_power.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/kron_g500-logn16/kron_g500-logn16.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/kron_g500-logn17/kron_g500-logn17.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/kron_g500-logn18/kron_g500-logn18.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/kron_g500-logn19/kron_g500-logn19.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/kron_g500-logn20/kron_g500-logn20.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/laminar_duct3D/laminar_duct3D.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/language/language.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/largebasis/largebasis.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/ldoor/ldoor.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/lhr34/lhr34.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/lhr34c/lhr34c.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/lhr71/lhr71.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/lhr71c/lhr71c.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/li/li.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/ljournal-2008/ljournal-2008.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Long_Coup_dt0/Long_Coup_dt0.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Long_Coup_dt6/Long_Coup_dt6.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/lowThrust_10/lowThrust_10.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/lowThrust_11/lowThrust_11.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/lowThrust_12/lowThrust_12.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/lowThrust_13/lowThrust_13.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/lowThrust_4/lowThrust_4.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/lowThrust_5/lowThrust_5.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/lowThrust_6/lowThrust_6.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/lowThrust_7/lowThrust_7.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/lowThrust_8/lowThrust_8.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/lowThrust_9/lowThrust_9.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/lp1/lp1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/luxembourg_osm/luxembourg_osm.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/m14b/m14b.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/mario001/mario001.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/mario002/mario002.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/mark3jac040sc/mark3jac040sc.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/mark3jac060sc/mark3jac060sc.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/me2010/me2010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/memplus/memplus.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/mip1/mip1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/ML_Laplace/ML_Laplace.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/mouse_gene/mouse_gene.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/msc10848/msc10848.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/msc23052/msc23052.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/msdoor/msdoor.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/m_t1/m_t1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/mult_dcop_01/mult_dcop_01.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/mult_dcop_02/mult_dcop_02.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/mult_dcop_03/mult_dcop_03.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/NACA0015/NACA0015.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/nasasrb/nasasrb.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/nd12k/nd12k.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/nd24k/nd24k.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/nd6k/nd6k.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/net100/net100.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/net125/net125.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/net150/net150.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/net4-1/net4-1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/net50/net50.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/net75/net75.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/netherlands_osm/netherlands_osm.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/nh2010/nh2010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/NLR/NLR.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/NotreDame_www/NotreDame_www.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/nv2010/nv2010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/ohne2/ohne2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/oilpan/oilpan.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/olafu/olafu.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/onetone2/onetone2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/OPF_10000/OPF_10000.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/opt1/opt1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/p2p-Gnutella31/p2p-Gnutella31.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/parabolic_fem/parabolic_fem.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/patents/patents.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/pattern1/pattern1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/pcrystk02/pcrystk02.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/pcrystk03/pcrystk03.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/pct20stif/pct20stif.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/pdb1HYS/pdb1HYS.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/pds10/pds10.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/PFlow_742/PFlow_742.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/pkustk01/pkustk01.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/pkustk02/pkustk02.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/pkustk03/pkustk03.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/pkustk04/pkustk04.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/pkustk05/pkustk05.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/pkustk06/pkustk06.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/pkustk07/pkustk07.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/pkustk08/pkustk08.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/pkustk09/pkustk09.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/pkustk10/pkustk10.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/pkustk11/pkustk11.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/pkustk12/pkustk12.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/pkustk13/pkustk13.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/pkustk14/pkustk14.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/pli/pli.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/PR02R/PR02R.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Pres_Poisson/Pres_Poisson.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/pwtk/pwtk.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/qa8fk/qa8fk.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/qa8fm/qa8fm.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/raefsky3/raefsky3.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/raefsky4/raefsky4.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/rajat15/rajat15.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/rajat22/rajat22.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/rajat26/rajat26.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/rajat29/rajat29.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/rajat30/rajat30.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/ramage02/ramage02.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Reuters911/Reuters911.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/rgg_n_2_15_s0/rgg_n_2_15_s0.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/rgg_n_2_22_s0/rgg_n_2_22_s0.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/ri2010/ri2010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/rim/rim.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/RM07R/RM07R.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/rma10/rma10.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/roadNet-CA/roadNet-CA.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/roadNet-PA/roadNet-PA.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/roadNet-TX/roadNet-TX.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/s3dkq4m2/s3dkq4m2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/s3dkt3m2/s3dkt3m2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/s4dkt3m2/s4dkt3m2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Serena/Serena.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/shermanACb/shermanACb.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/ship_001/ship_001.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/ship_003/ship_003.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/shipsec1/shipsec1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/shipsec5/shipsec5.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/shipsec8/shipsec8.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Si10H16/Si10H16.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Si34H36/Si34H36.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Si41Ge41H72/Si41Ge41H72.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Si5H12/Si5H12.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Si87H76/Si87H76.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/sinc15/sinc15.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/SiO/SiO.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/SiO2/SiO2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/skirt/skirt.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/smallworld/smallworld.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/sme3Dc/sme3Dc.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/smt/smt.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/soc-LiveJournal1/soc-LiveJournal1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/soc-sign-Slashdot090221/soc-sign-Slashdot090221.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/sparsine/sparsine.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/srb1/srb1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Stanford/Stanford.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/std1_Jac2/std1_Jac2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/std1_Jac3/std1_Jac3.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/stokes128/stokes128.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/stokes64/stokes64.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/struct3/struct3.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/t2dah/t2dah.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/t2dah_a/t2dah_a.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/t2dah_e/t2dah_e.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/t3dh/t3dh.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/t3dh_a/t3dh_a.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/t3dh_e/t3dh_e.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/t3dl/t3dl.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/t3dl_a/t3dl_a.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/tandem_vtx/tandem_vtx.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/ted_A/ted_A.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/ted_AB/ted_AB.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/ted_AB_unscaled/ted_AB_unscaled.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/ted_A_unscaled/ted_A_unscaled.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/ted_B_unscaled/ted_B_unscaled.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/thread/thread.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/tmt_sym/tmt_sym.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/torso1/torso1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/transient/transient.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/trdheim/trdheim.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Trefethen_20000/Trefethen_20000.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Trefethen_20000b/Trefethen_20000b.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/troll/troll.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/TSOPF_FS_b162_c1/TSOPF_FS_b162_c1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/TSOPF_FS_b162_c3/TSOPF_FS_b162_c3.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/TSOPF_FS_b162_c4/TSOPF_FS_b162_c4.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/TSOPF_FS_b300/TSOPF_FS_b300.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/TSOPF_FS_b300_c1/TSOPF_FS_b300_c1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/TSOPF_FS_b300_c2/TSOPF_FS_b300_c2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/TSOPF_FS_b300_c3/TSOPF_FS_b300_c3.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/TSOPF_FS_b39_c19/TSOPF_FS_b39_c19.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/TSOPF_FS_b39_c30/TSOPF_FS_b39_c30.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/TSOPF_FS_b39_c7/TSOPF_FS_b39_c7.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/TSOPF_FS_b9_c6/TSOPF_FS_b9_c6.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/TSOPF_RS_b162_c3/TSOPF_RS_b162_c3.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/TSOPF_RS_b162_c4/TSOPF_RS_b162_c4.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/TSOPF_RS_b2052_c1/TSOPF_RS_b2052_c1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/TSOPF_RS_b2383/TSOPF_RS_b2383.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/TSOPF_RS_b2383_c1/TSOPF_RS_b2383_c1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/TSOPF_RS_b300_c1/TSOPF_RS_b300_c1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/TSOPF_RS_b300_c2/TSOPF_RS_b300_c2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/TSOPF_RS_b300_c3/TSOPF_RS_b300_c3.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/TSOPF_RS_b39_c19/TSOPF_RS_b39_c19.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/TSOPF_RS_b39_c30/TSOPF_RS_b39_c30.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/TSOPF_RS_b39_c7/TSOPF_RS_b39_c7.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/TSOPF_RS_b678_c1/TSOPF_RS_b678_c1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/TSOPF_RS_b678_c2/TSOPF_RS_b678_c2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/tsyl201/tsyl201.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/tube1/tube1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/tube2/tube2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/turon_m/turon_m.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/usroads/usroads.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/usroads-48/usroads-48.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/vanbody/vanbody.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/venturiLevel3/venturiLevel3.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/vibrobox/vibrobox.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/viscorocks/viscorocks.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/vsp_barth5_1Ksep_50in_5Kout/vsp_barth5_1Ksep_50in_5Kout.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/vsp_bcsstk30_500sep_10in_1Kout/vsp_bcsstk30_500sep_10in_1Kout.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/vsp_befref_fxm_2_4_air02/vsp_befref_fxm_2_4_air02.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/vsp_bump2_e18_aa01_model1_crew1/vsp_bump2_e18_aa01_model1_crew1.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/vsp_c-30_data_data/vsp_c-30_data_data.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/vsp_c-60_data_cti_cs4/vsp_c-60_data_cti_cs4.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/vsp_finan512_scagr7-2c_rlfddd/vsp_finan512_scagr7-2c_rlfddd.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/vsp_mod2_pgp2_slptsk/vsp_mod2_pgp2_slptsk.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/vsp_model1_crew1_cr42_south31/vsp_model1_crew1_cr42_south31.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/vsp_msc10848_300sep_100in_1Kout/vsp_msc10848_300sep_100in_1Kout.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/vsp_p0291_seymourl_iiasa/vsp_p0291_seymourl_iiasa.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/vsp_sctap1-2b_and_seymourl/vsp_sctap1-2b_and_seymourl.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/vsp_south31_slptsk/vsp_south31_slptsk.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/vsp_vibrobox_scagr7-2c_rlfddd/vsp_vibrobox_scagr7-2c_rlfddd.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/vt2010/vt2010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/wathen100/wathen100.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/wathen120/wathen120.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/web-Google/web-Google.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/web-NotreDame/web-NotreDame.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/wikipedia-20051105/wikipedia-20051105.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/wikipedia-20060925/wikipedia-20060925.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/wikipedia-20061104/wikipedia-20061104.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/wikipedia-20070206/wikipedia-20070206.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/wiki-Talk/wiki-Talk.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/windscreen/windscreen.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/wing_nodal/wing_nodal.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/wy2010/wy2010.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/x104/x104.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Zd_Jac2/Zd_Jac2.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Zd_Jac3/Zd_Jac3.tar.gz
wget https://www.cise.ufl.edu/research/sparse/MM/Zd_Jac6/Zd_Jac6.tar.gz
wget https://dataset-ppopp.oss-cn-beijing.aliyuncs.com/dataset2/GitHub.tar.gz
wget https://dataset-ppopp.oss-cn-beijing.aliyuncs.com/dataset2/artist.tar.gz
wget https://dataset-ppopp.oss-cn-beijing.aliyuncs.com/dataset2/ell.tar.gz
wget https://dataset-ppopp.oss-cn-beijing.aliyuncs.com/dataset2/amazon.tar.gz
wget https://dataset-ppopp.oss-cn-beijing.aliyuncs.com/dataset2/amazon0505.tar.gz
wget https://dataset-ppopp.oss-cn-beijing.aliyuncs.com/dataset2/dd.tar.gz
wget https://dataset-ppopp.oss-cn-beijing.aliyuncs.com/dataset2/yelp.tar.gz
wget https://dataset-ppopp.oss-cn-beijing.aliyuncs.com/dataset2/comamazon.tar.gz
wget https://dataset-ppopp.oss-cn-beijing.aliyuncs.com/dataset2/IGB_small.tar.gz
wget https://dataset-ppopp.oss-cn-beijing.aliyuncs.com/dataset2/AmazonProducts.tar.gz
wget https://dataset-ppopp.oss-cn-beijing.aliyuncs.com/dataset2/ogb.tar.gz
wget https://dataset-ppopp.oss-cn-beijing.aliyuncs.com/dataset2/reddit.tar.gz
wget https://dataset-ppopp.oss-cn-beijing.aliyuncs.com/dataset2/IGB_medium.tar.gz
wget https://dataset-ppopp.oss-cn-beijing.aliyuncs.com/dataset2/yeast.tar.gz
wget https://dataset-ppopp.oss-cn-beijing.aliyuncs.com/dataset2/blog.tar.gz


find . -name '*.tar.gz' -exec tar xvf {} \; 
-exec rm {} \;
cp ../conv.c .
gcc -O3 -o conv conv.c

for i in `ls -d */`
do
cd ${i}
ii=${i/\//}
mv ${ii}.mtx ${ii}.mt0
../conv ${ii}.mt0 ${ii}.mtx 
rm ${ii}.mt0
cd ..
done

rm conv
rm conv.c
cd ..
